---

  - include: selinux.yml

  - name: search sonarqube image
    shell: docker inspect sonarqube:{{sonar_version}}
    ignore_errors: yes
    register: search_sonarqube_response

  - include: sonarqube-build-container.yml
    when: search_sonarqube_response|failed

  - file: path=/var/log/sonarqube state=directory

  - shell: chcon -Rt svirt_sandbox_file_t /var/log/sonarqube
    when: selinux_status.rc != 0

  - file: path=/etc/sonarqube state=directory

  - file: path=/var/lib/sonarqube/temp state=directory

  - shell: chcon -Rt svirt_sandbox_file_t /var/lib/sonarqube/temp
    when: selinux_status.rc != 0

  - file: path=/var/lib/sonarqube/data state=directory

  - shell: chcon -Rt svirt_sandbox_file_t /var/lib/sonarqube/data
    when: selinux_status.rc != 0

  - file: path=/var/lib/sonarqube/extensions/plugins state=directory

  - shell: chcon -Rt svirt_sandbox_file_t /var/lib/sonarqube/extensions/plugins
    when: selinux_status.rc != 0

  - name: ensure sonarqube container is running
    docker:
      image: "sonarqube:{{sonar_version}}"
      memory_limit: 1024MB
      name: sonarqube
      links: "{{db_name}}:{{db_name}}"
      ports: "{{sonar_interface}}:{{sonar_port}}:9000"
      state: reloaded
      restart_policy: always
      volumes:
        /var/lib/sonarqube/data:/opt/sonarqube/data:rw
        /var/lib/sonarqube/temp:/opt/sonarqube/temp:rw
        /var/lib/sonarqube/extensions/plugins:/opt/sonarqube/extensions/plugins:rw
        /var/log/sonarqube:/opt/sonarqube/logs:rw
    register: start_sonarqube

